#!/bin/bash
#
# Perform necessary puppet-library removal steps
# after package is uninstalled.
#

PROGNAME=$(basename $0)
PKGNAME="puppet-library"
DEST_DIR="/opt/$PKGNAME"
CONF_DIR="/etc/$PKGNAME"
MOD_DIR="/var/lib/modules"
LOG_DIR="/var/log/$PKGNAME"
NGINX_LOG_DIR="$LOG_DIR/nginx"

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# Remove installed directory
rm -rf $DEST_DIR

echo "puppet-library has been uninstalled!"

exit 0
