#!/bin/bash
#
# Perform necessary puppet-library setup steps
# prior to installing package.
#

PROGNAME=$(basename $0)
PKGNAME="puppet-library"
DEST_DIR="/opt/$PKGNAME"
CONF_DIR="/etc/$PKGNAME"
MOD_DIR="/var/lib/modules"
LOG_DIR="/var/log/$PKGNAME"
NGINX_LOG_DIR="$LOG_DIR/nginx"

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

echo "Stopping nginx"
$DEST_DIR/embedded/etc/init.d/nginx stop || error_exit "Cannot stop service"

exit 0
